### ISSUE TITLE
The File Name should include at least one dot.

### ISSUE THREAD

**Issue by NoobToolzz** [ShufflePerson/Discord_CDN#4]
I get this error after pasting (really any) URL.

Server can be accessed from http://localhost:80
The File Name should include at least one dot.

URL I used this time: https://cdn.discordapp.com/attachments/846397893145526284/981211319380348948/RoGold.rar

**Comment by ShufflePerson** [comment]
Have you tried both of these URLs? 

`http://localhost/attachments/846397893145526284/981211319380348948/RoGold.rar`
and
`http://localhost/https://cdn.discordapp.com/attachments/846397893145526284/981211319380348948/RoGold.rar`

**Comment by NoobToolzz** [comment]
> Have you tried both of these URLs? 
> 
> `http://localhost/attachments/846397893145526284/981211319380348948/RoGold.rar`
> and
> `http://localhost/https://cdn.discordapp.com/attachments/846397893145526284/981211319380348948/RoGold.rar`
> 
> Edit: I've tested it with your URL and seems the file is deleted. Worked fine with any other URL

Yes, I tried both combinations. They led to the same output.

**Comment by ShufflePerson** [comment]
Can you provide the exact URL you are visiting. Failing to re-produce on my end

**Comment by NoobToolzz** [comment]
> Can you provide the exact URL you are visiting. Failing to re-produce on my end

The url is the one I gave in the first comment. Or you can find it from [here](https://robloxscripts.com/rogold-cracked-1-3-0/). As for the localhost url I visited both the ones you specified above.

**Comment by ShufflePerson** [comment]
> > Can you provide the exact URL you are visiting. Failing to re-produce on my end
> 
> The url is the one I gave in the first comment. Or you can find it from [here](https://robloxscripts.com/rogold-cracked-1-3-0/). As for the localhost url I visited both the ones you specified above.

What browser are you using? Can you try simply doing a curl. 
Only thing different from our setups is the browser and the port.

**Comment by NoobToolzz** [comment]
I tried `curl "https://cdn.discordapp.com/attachments/846397893145526284/981211319380348948/RoGold.rar?ex=66310840&is=661e9340&hm=f069355f1f4054ce952b2bf81913470c533f6fe362c9b27ec6e6fe42c785cb71&"` and it returned this.

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: discord/attachments/846397893145526284/981211319380348948/RoGold.rar</Details></Error>
```

**Comment by ShufflePerson** [comment]
The file you want is deleted.
