### ISSUE TITLE
    data: { message: '401: Unauthorized', code: 0 }

### ISSUE THREAD

**Issue by ZeroxDayz** [ShufflePerson/Discord_CDN#6]
It is giving me this error

**Comment by ShufflePerson** [comment]
Hey,

Did you configure the token properly in the .env file?

**Comment by ShufflePerson** [comment]
No ways that I am aware of. You can create a new Discord account and use the token of that account.

**Comment by Puyodead1** [comment]
> Sorry I was sleep deprived I realized it has to be a user-token and not a bot-token. Is there a way you know to use a bot token to do this or something similar?

it works fine with bot tokens, the header needs to be prefixed with `Bot` like normal bot requests.

**Comment by ShufflePerson** [comment]
> > Sorry I was sleep deprived I realized it has to be a user-token and not a bot-token. Is there a way you know to use a bot token to do this or something similar?
> 
> it works fine with bot tokens, the header needs to be prefixed with `Bot` like normal bot requests.

Thank you for letting us know. I'll see if I find the time to add it as a feature flag, if not, all PRs are welcome ;)
