### ISSUE TITLE
Rarely `.env` cannot really update the environment variables problem

### ISSUE THREAD

**Issue by LianSheng197** [ShufflePerson/Discord_CDN#9]
There is an issue with `.env` files not being updated to the current environment variables.  
This seems to be a problem with `dotnet` or `tsc` or `node`.  
(Or maybe it's a problem with the operating system itself.)

The exact cause is unknown, and the exact solution is unknown.  
When the problem occurs, even if I reopen the terminal or shell or even run `unset <variable-name>`, it is not resolved.

This should not be a generalized problem, but we might want to pay more attention to whether or not  to use `.env` as an environment variable file in the future.

**Some information**
```
     OS: Ubuntu 22.04.4 LTS x86_64
 Kernel: 6.5.0-28-generic
  Shell: bash 5.1.16
--------------------------------------------------------
   Node: v18.12.1
    npm: 8.19.2
Command: npm run start
 Script: (start) tsc && node ./dist/server.js
```

**Comment by LianSheng197** [comment]
At the same time, it seems to be difficult to manage multiple TOKENs with the currently adopted scheme.

Maybe I don't know enough about the `.env` file format.  
But [my current modification](https://github.com/LianSheng197/Discord_CDN/blob/774c98fbd4fd0e059a82445c7935574d62fcfc17/src/Discord/Utils/VerifyToken.ts#L35) uses `,[\ \t]*` as split regex.
The spaces ` ` allowed after the comma `,` are purely for readability.

**Comment by LianSheng197** [comment]
Although there are no recent information, but some related questions:
- [(2019) StackOverFlow: why i am not able to update env variable in node js](https://stackoverflow.com/questions/58425890)
- [(2020) StackOverFlow: NodeJS .env variables (using dotenv) are not submitting to change -- cached?](https://stackoverflow.com/questions/61757752)
- [(2020) GitHub Issue: .env file variables are cached #75](https://github.com/goatandsheep/react-native-dotenv/issues/75)

**Comment by ShufflePerson** [comment]
Run `npm cache clean --force`

**Comment by LianSheng197** [comment]
I'll try this if it happens again. :smile: 
However, is it possible to keep this issue open for the time being? Because this solution may not work for me. I need to check it for a while.

**Comment by ShufflePerson** [comment]
> I'll try this if it happens again. 😄 However, is it possible to keep this issue open for the time being? Because this solution may not work for me. I need to check it for a while.

You can reopen the issue even after I close it. Let me know!
